services:
  remix-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./prisma/dev.db:/app/prisma/dev.db
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npx prisma migrate deploy && npm run dev"
